#define T23_ON            (1)
#define T23_32BIT_MODE_ON (1)

typedef enum {
        UART1 = 0,
        UART2,
        UART_NUMBER_OF_MODULES
} UART_MODULE;

typedef enum {
        INT_PRIORITY_DISABLED = 0,
        INT_PRIORITY_LEVEL_1  = 1,
        INT_PRIORITY_LEVEL_2  = 2,
        INT_PRIORITY_LEVEL_3  = 3,
        INT_PRIORITY_LEVEL_4  = 4,
        INT_PRIORITY_LEVEL_5  = 5,
        INT_PRIORITY_LEVEL_6  = 6,
        INT_PRIORITY_LEVEL_7  = 7
} INT_PRIORITY;

typedef enum {
        INT_SUB_PRIORITY_LEVEL_0 = 0,
        INT_SUB_PRIORITY_LEVEL_1 = 1,
        INT_SUB_PRIORITY_LEVEL_2 = 2,
        INT_SUB_PRIORITY_LEVEL_3 = 3
} INT_SUB_PRIORITY;

typedef enum {
        INT_CT = 0,
        INT_CS0,
        INT_CS1,
        INT_INT0,
        INT_INT1,
        INT_INT2,
        INT_INT3,
        INT_INT4,
        INT_T1,
        INT_T2,
        INT_T3,
        INT_T4,
        INT_T5,
        INT_IC1,
        INT_IC2,
        INT_IC3,
        INT_IC4,
        INT_IC5,
        INT_IC1E,
        INT_IC2E,
        INT_IC3E,
        INT_IC4E,
        INT_IC5E,
        INT_OC1,
        INT_OC2,
        INT_OC3,
        INT_OC4,
        INT_OC5,
        INT_CNA,
        INT_CNB,
        INT_CNC,
        INT_SPI1,
        INT_SPI2,
        INT_SPI1E,
        INT_SPI2E,
        INT_SPI1TX,
        INT_SPI2TX,
        INT_SPI1RX,
        INT_SPI2RX,
        INT_I2C1,
        INT_I2C2,
        INT_I2C1B,
        INT_I2C2B,
        INT_I2C1S,
        INT_I2C2S,
        INT_I2C1M,
        INT_I2C2M,
        INT_U1,
        INT_U2,
        INT_U1E,
        INT_U2E,
        INT_U1RX,
        INT_U2RX,
        INT_U1TX,
        INT_U2TX,
        INT_AD1,
        INT_PMP,
        INT_PMPE,
        INT_CMP1,
        INT_CMP2,
        INT_CMP3,
        INT_FSCM,
        INT_FCE,
        INT_RTCC,
        INT_CTMU,
        INT_DMA0,
        INT_DMA1,
        INT_DMA2,
        INT_DMA3,
        INT_USB,
        INT_NUM
} INT_SOURCE;

typedef enum {
        INT_CORE_TIMER_VECTOR,
        INT_CORE_SOFTWARE_0_VECTOR,
        INT_CORE_SOFTWARE_1_VECTOR,
        INT_EXTERNAL_0_VECTOR,
        INT_EXTERNAL_1_VECTOR,
        INT_EXTERNAL_2_VECTOR,
        INT_EXTERNAL_3_VECTOR,
        INT_EXTERNAL_4_VECTOR,
        INT_TIMER_1_VECTOR,
        INT_TIMER_2_VECTOR,
        INT_TIMER_3_VECTOR,
        INT_TIMER_4_VECTOR,
        INT_TIMER_5_VECTOR,
        INT_INPUT_CAPTURE_1_VECTOR,
        INT_INPUT_CAPTURE_2_VECTOR,
        INT_INPUT_CAPTURE_3_VECTOR,
        INT_INPUT_CAPTURE_4_VECTOR,
        INT_INPUT_CAPTURE_5_VECTOR,
        INT_OUTPUT_COMPARE_1_VECTOR,
        INT_OUTPUT_COMPARE_2_VECTOR,
        INT_OUTPUT_COMPARE_3_VECTOR,
        INT_OUTPUT_COMPARE_4_VECTOR,
        INT_OUTPUT_COMPARE_5_VECTOR,
        INT_SPI_1_VECTOR,
        INT_SPI_2_VECTOR,
        INT_UART_1_VECTOR,
        INT_UART_2_VECTOR,
        INT_I2C_1_VECTOR,
        INT_I2C_2_VECTOR,
        INT_CHANGE_NOTICE_VECTOR,
        INT_ADC_VECTOR,
        INT_PMP_VECTOR,
        INT_COMPARATOR_1_VECTOR,
        INT_COMPARATOR_2_VECTOR,
        INT_COMPARATOR_3_VECTOR,
        INT_FAIL_SAFE_MONITOR_VECTOR,
        INT_RTCC_VECTOR,
        INT_CTMU_VECTOR,
        INT_DMA_0_VECTOR,
        INT_DMA_1_VECTOR,
        INT_DMA_2_VECTOR,
        INT_DMA_3_VECTOR,
        INT_FCE_VECTOR,
        INT_USB_1_VECTOR,
} INT_VECTOR;
